apiVersion: v1
kind: Service
metadata:
  name: finance-backend-service
spec:
  type: NodePort
  selector:
    app: finance-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
